version: "3.9"

services:
  backend:
    build: ./backend
    container_name: noto-backend
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGO_URI: mongodb://noto:root@mongo:27017/notoDB?authSource=admin
    depends_on:
      - mongo
    networks:
      - noto-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: noto-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - noto-network
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: noto-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: noto
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - noto-network
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

networks:
  noto-network:
    driver: bridge

volumes:
  mongo-data:
